// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB7rcLzvPERowbPbVSD-K9kMrISLwaJR0',
    appId: '1:578896536791:web:7a1ad85941800e9d577c92',
    messagingSenderId: '578896536791',
    projectId: 'isvara-bd2eb',
    authDomain: 'isvara-bd2eb.firebaseapp.com',
    storageBucket: 'isvara-bd2eb.appspot.com',
    measurementId: 'G-LN40FSMB78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_fOrBYpMk98R83vvyvH48d2jxX7kO4-0',
    appId: '1:578896536791:android:91b59d99f99abbd6577c92',
    messagingSenderId: '578896536791',
    projectId: 'isvara-bd2eb',
    storageBucket: 'isvara-bd2eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFUEQ_aw6KikwpPQ-eP2GUi0sZfdhO_oY',
    appId: '1:578896536791:ios:39d25438e44a7664577c92',
    messagingSenderId: '578896536791',
    projectId: 'isvara-bd2eb',
    storageBucket: 'isvara-bd2eb.appspot.com',
    iosClientId: '578896536791-eethuilmpimpp35vgse1tctt8nftgghf.apps.googleusercontent.com',
    iosBundleId: 'com.example.isvaraf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFUEQ_aw6KikwpPQ-eP2GUi0sZfdhO_oY',
    appId: '1:578896536791:ios:39d25438e44a7664577c92',
    messagingSenderId: '578896536791',
    projectId: 'isvara-bd2eb',
    storageBucket: 'isvara-bd2eb.appspot.com',
    iosClientId: '578896536791-eethuilmpimpp35vgse1tctt8nftgghf.apps.googleusercontent.com',
    iosBundleId: 'com.example.isvaraf',
  );
}
